-- 0049_lead_intent_summary.sql
-- 8.1 — Returning-bride vendor notification caching.
-- Stores a one-line agent-extracted summary of what a returning bride
-- is asking about, so subsequent follow-ups can reuse without re-extraction.

alter table leads
  add column if not exists intent_summary text,
  add column if not exists intent_summary_at timestamptz;

comment on column leads.intent_summary is
  'One-line summary of the bride''s current ask, generated by Haiku from her follow-up message. Reused across subsequent messages until the topic shifts or 30 days pass.';

comment on column leads.intent_summary_at is
  'When intent_summary was last refreshed. Used to age out stale summaries.';
