-- 0119_prospect_discard.sql — TDW_05 Block 05, P3-D (the prospect lane's exit door).
-- FOUNDER-RUN in the Supabase SQL editor. Rides the deploy ZIP as a FILE; it is
-- applied to production by the founder's hand alone, never by a deploy.
-- Project: nvzkbagqxbysoeszxent (public plane — `prospects` appears 0 times in
-- docs/db/ENGINE_SCHEMA.md, counted; Plane Doctrine satisfied by command).
--
-- CE-30 · R-30.10 / R-30.12, ruled 2026-08-11.
--
-- ══ PROVENANCE, PER STATEMENT (the SQL-provenance law) ═══════════════════════
-- STATEMENT 1 + 2 — the constraint NAME and its seven current values:
--   SETTLING WITNESS: the founder's paste of 2026-08-11, run in the Supabase SQL
--   editor against production —
--     SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
--     WHERE conrelid = 'public.prospects'::regclass AND contype = 'c';
--   returning `prospects_state_check` over exactly
--     'cold','templated','replied','in_session','converted','opted_out','expired'.
--   STARTING WITNESS, byte-matched against it: docs/db/PUBLIC_SCHEMA.md:1516-1517
--   (CONSTRAINTS ADDENDUM, snapshot 2026-07-23, applied ladder tip 0099).
--   THE NAME IS NOT IN 0085. That migration spells the CHECK inline
--   (0085_prospect_lane.sql:31-32), so Postgres auto-named it; the name is
--   knowable only from a live catalogue read, which is why statement 1 could not
--   have been authored from the migration ladder alone.
-- STATEMENT 3 — that no `discarded_at` exists to collide with:
--   docs/db/PUBLIC_SCHEMA.md:737-753, `public.prospects · 14 columns`, the list
--   ending at `updated_at`.
--
-- ══ THE REVERSE DIRECTION IS WITHHELD ════════════════════════════════════════
-- Per the conditional-withheld rule: alternate-direction SQL never ships beside
-- the block it conditions, because anything runnable left in a transcript will be
-- run (the E-1 mishap — a split block and its collapse pasted seventeen seconds
-- apart). The reverse exists, it is the founder's on a ruling, and it is handed
-- in a LATER message once the forward direction is confirmed applied.
-- NOTE FOR WHOEVER ASKS FOR IT: reverting the CHECK requires that no row sits in
-- state 'discarded' at that moment, exactly as 0085's own revert note says of
-- 'prospect_marketing'.
--
-- IMMUTABILITY: never edit an applied migration. Corrections go in 0120+.
-- AFTER APPLYING: docs/db/PUBLIC_SCHEMA.md is regenerated by the PAIR
-- (db/queries/public_schema_dump.sql + db/queries/format_public_schema.js).
-- This migration does not hand-edit that witnessed file.

-- ── (1) drop the auto-named CHECK, BY ITS WITNESSED NAME ─────────────────────
-- No `if exists`, deliberately. The name came from a live catalogue read; if it
-- does not resolve, the premise of this migration is wrong and the whole block
-- must fail loudly rather than skip a statement and half-apply. A silent skip here
-- would leave statement 2 adding a SECOND check constraint beside the first, and
-- the table would then accept nothing that both lists do not admit — a failure
-- that surfaces days later as an unexplained write refusal.
alter table public.prospects drop constraint prospects_state_check;

-- ── (2) re-add it, admitting the eighth value ────────────────────────────────
-- The seven are carried over VERBATIM from the pasted definition — this is a
-- WIDEN, and a re-typed list is how a widen quietly becomes a narrow.
alter table public.prospects add constraint prospects_state_check
  check (state in ('cold', 'templated', 'replied', 'in_session', 'converted',
                   'opted_out', 'expired', 'discarded'));

-- ── (3) the discard stamp ────────────────────────────────────────────────────
-- R-30.12, F3 arm (b). `updated_at` cannot answer "when did we drop them":
-- `updateProspect` (src/lib/prospects.js:106) stamps it on EVERY write, so the
-- first later touch overwrites the only record of the discard. Nullable with no
-- default: a null here means "not discarded", and the restore verb clears it, so
-- the column and the state never give two different answers.
alter table public.prospects add column if not exists discarded_at timestamptz;
