import os

with open('src/api/vendor/invoices.js', 'r') as f:
    content = f.read()

# 1. Add new requires
old_req = (
    "const express        = require('express');\n"
    "const router         = express.Router();\n"
    "const requireAuth    = require('../middleware/requireAuth');\n"
    "const resolveVendor  = require('../middleware/resolveVendor');"
)
new_req = (
    "const express        = require('express');\n"
    "const router         = express.Router();\n"
    "const requireAuth    = require('../middleware/requireAuth');\n"
    "const resolveVendor  = require('../middleware/resolveVendor');\n"
    "const asyncHandler         = require('../../lib/asyncHandler');\n"
    "const { ok: okRes, err: errRes } = require('../../lib/response');\n"
    "const { createInvoice, updateInvoice } = require('../../lib/vendor/invoices');\n"
    "const { generateInvoicePdf }  = require('../../lib/invoicePdf');\n"
    "const { buildInvoiceMessage } = require('../../lib/invoiceMessage');"
)
content = content.replace(old_req, new_req, 1)

# 2. Add deleted_at IS NULL filter to GET list
content = content.replace(
    "  let listQuery = supabase.from('invoices')\n"
    "    .select('id, invoice_number, client_name, amount_total, amount_paid, state, due_date, created_at')\n"
    "    .eq('vendor_id', vendor.id);",

    "  let listQuery = supabase.from('invoices')\n"
    "    .select('id, invoice_number, client_name, amount_total, amount_paid, state, due_date, created_at')\n"
    "    .eq('vendor_id', vendor.id)\n"
    "    .is('deleted_at', null);",
    1
)
content = content.replace(
    "  let countQuery = supabase.from('invoices')\n"
    "    .select('*', { count: 'exact', head: true })\n"
    "    .eq('vendor_id', vendor.id);",

    "  let countQuery = supabase.from('invoices')\n"
    "    .select('*', { count: 'exact', head: true })\n"
    "    .eq('vendor_id', vendor.id)\n"
    "    .is('deleted_at', null);",
    1
)
content = content.replace(
    "  const summaryQuery = supabase.from('invoices')\n"
    "    .select('amount_total, amount_paid, state')\n"
    "    .eq('vendor_id', vendor.id);",

    "  const summaryQuery = supabase.from('invoices')\n"
    "    .select('amount_total, amount_paid, state')\n"
    "    .eq('vendor_id', vendor.id)\n"
    "    .is('deleted_at', null);",
    1
)

# 3. Replace the cancel handler and append new endpoints
old_cancel = (
    "router.patch('/:invoiceId/cancel', requireAuth, async (req, res) => {\n"
    "  const supabase   = req.app.locals.supabase;\n"
    "  const { user_id } = req.auth;\n"
    "  const { invoiceId } = req.params;\n"
    "\n"
    "  // Resolve vendor\n"
    "  const { data: userRow } = await supabase.from('users').select('id').eq('id', user_id).maybeSingle();\n"
    "  if (!userRow) return res.status(403).json({ ok: false, error: 'User not found.' });\n"
    "  const { data: vendorRow } = await supabase.from('vendors').select('id').eq('user_id', user_id).maybeSingle();\n"
    "  if (!vendorRow) return res.status(403).json({ ok: false, error: 'Vendor not found.' });\n"
    "\n"
    "  const { data: inv, error: fetchErr } = await supabase\n"
    "    .from('invoices').select('id, invoice_number, client_name, state')\n"
    "    .eq('id', invoiceId).eq('vendor_id', vendorRow.id).single();\n"
    "\n"
    "  if (fetchErr?.code === 'PGRST116' || !inv) return res.status(404).json({ ok: false, error: 'Invoice not found.' });\n"
    "  if (fetchErr) return res.status(500).json({ ok: false, error: fetchErr.message });\n"
    "  if (inv.state === 'cancelled') return res.json({ ok: true, already_cancelled: true, message: `${inv.invoice_number} was already cancelled.` });\n"
    "  if (inv.state === 'paid') return res.status(400).json({ ok: false, error: 'Cannot cancel a fully paid invoice.' });\n"
    "\n"
    "  const { error: cancelErr } = await supabase\n"
    "    .from('invoices').update({ state: 'cancelled' })\n"
    "    .eq('id', invoiceId).eq('vendor_id', vendorRow.id);\n"
    "\n"
    "  if (cancelErr) return res.status(500).json({ ok: false, error: cancelErr.message });\n"
    "\n"
    "  console.log(`[invoices:cancel] ${inv.invoice_number} cancelled by vendor ${vendorRow.id}`);\n"
    "  return res.json({ ok: true, message: `${inv.client_name}'s invoice ${inv.invoice_number} cancelled.` });\n"
    "});\n"
    "\n"
    "module.exports = router;"
)

new_handlers = (
    "// ─── PATCH /api/v2/vendor/invoices/:invoiceId/cancel ──────────────────\n"
    "//\n"
    "// Cancel invoice. Preserved for dreamai list page CRUD.\n"
    "// Auth: requireAuth. resolveVendor mode C via invoices table.\n"
    "\n"
    "router.patch('/:invoiceId/cancel', requireAuth, resolveVendor({ paramName: 'invoiceId', via: 'invoices' }), asyncHandler(async (req, res) => {\n"
    "  const supabase   = req.app.locals.supabase;\n"
    "  const vendor     = req.vendor;\n"
    "  const invoiceId  = req.params.invoiceId;\n"
    "\n"
    "  const { data: inv, error: fetchErr } = await supabase\n"
    "    .from('invoices').select('id, invoice_number, client_name, state')\n"
    "    .eq('id', invoiceId).eq('vendor_id', vendor.id).is('deleted_at', null).single();\n"
    "\n"
    "  if (fetchErr?.code === 'PGRST116' || !inv) return errRes(res, 404, 'Invoice not found.');\n"
    "  if (fetchErr) return errRes(res, 500, fetchErr.message);\n"
    "  if (inv.state === 'cancelled') return okRes(res, { already_cancelled: true });\n"
    "  if (inv.state === 'paid') return errRes(res, 400, 'Cannot cancel a fully paid invoice.');\n"
    "\n"
    "  const { error: cancelErr } = await supabase\n"
    "    .from('invoices').update({ state: 'cancelled' })\n"
    "    .eq('id', invoiceId).eq('vendor_id', vendor.id);\n"
    "\n"
    "  if (cancelErr) return errRes(res, 500, cancelErr.message);\n"
    "  console.log('[invoices:cancel] ' + inv.invoice_number + ' cancelled by vendor ' + vendor.id);\n"
    "  return okRes(res, { invoice: { id: invoiceId, state: 'cancelled' } });\n"
    "}));\n"
    "\n"
    "// ─── POST /api/v2/vendor/invoices ──────────────────────────────────────\n"
    "//\n"
    "// Create invoice. Auto-assigns invoice_number. Counter never resets.\n"
    "// Auth: requireAuth. resolveVendor mode A.\n"
    "\n"
    "router.post('/', requireAuth, resolveVendor(), asyncHandler(async (req, res) => {\n"
    "  const supabase = req.app.locals.supabase;\n"
    "  const vendor   = req.vendor;\n"
    "  const body     = req.body || {};\n"
    "\n"
    "  const result = await createInvoice(supabase, vendor.id, {\n"
    "    client_name:    body.client_name    || null,\n"
    "    client_phone:   body.client_phone   || null,\n"
    "    client_id:      body.client_id      || null,\n"
    "    lead_id:        body.lead_id        || null,\n"
    "    description:    body.description    || null,\n"
    "    amount_total:   body.amount_total   || null,\n"
    "    amount_advance: body.amount_advance != null ? body.amount_advance : null,\n"
    "    due_date:       body.due_date       || null,\n"
    "    notes:          body.notes          || null,\n"
    "  });\n"
    "\n"
    "  if (!result.ok) return errRes(res, 400, result.error);\n"
    "  return okRes(res, { invoice: result.invoice, pdf_pending: true });\n"
    "}));\n"
    "\n"
    "// ─── PATCH /api/v2/vendor/invoices/:invoiceId ─────────────────────────\n"
    "//\n"
    "// Update invoice fields. Locked after any payment (amount_paid > 0).\n"
    "// Auth: requireAuth. resolveVendor mode C via invoices table.\n"
    "\n"
    "router.patch('/:invoiceId', requireAuth, resolveVendor({ paramName: 'invoiceId', via: 'invoices' }), asyncHandler(async (req, res) => {\n"
    "  const supabase  = req.app.locals.supabase;\n"
    "  const vendor    = req.vendor;\n"
    "  const invoiceId = req.params.invoiceId;\n"
    "  const body      = req.body || {};\n"
    "\n"
    "  const result = await updateInvoice(supabase, vendor.id, invoiceId, body);\n"
    "  if (!result.ok && result.code) return errRes(res, 409, result.error, result.code);\n"
    "  if (!result.ok) return errRes(res, 400, result.error);\n"
    "  return okRes(res, { invoice: result.invoice });\n"
    "}));\n"
    "\n"
    "// ─── POST /api/v2/vendor/invoices/:invoiceId/payments ─────────────────\n"
    "//\n"
    "// Record a payment. Calls the record_payment Postgres function.\n"
    "// Auth: requireAuth. resolveVendor mode C via invoices table.\n"
    "\n"
    "router.post('/:invoiceId/payments', requireAuth, resolveVendor({ paramName: 'invoiceId', via: 'invoices' }), asyncHandler(async (req, res) => {\n"
    "  const supabase  = req.app.locals.supabase;\n"
    "  const vendor    = req.vendor;\n"
    "  const invoiceId = req.params.invoiceId;\n"
    "  const body      = req.body || {};\n"
    "\n"
    "  const amount = Number(body.amount);\n"
    "  if (!amount || amount <= 0) return errRes(res, 400, 'amount must be greater than zero.');\n"
    "\n"
    "  const { data: result, error: fnErr } = await supabase\n"
    "    .rpc('record_payment', { p_invoice_id: invoiceId, p_amount: amount });\n"
    "\n"
    "  if (fnErr) return errRes(res, 500, fnErr.message);\n"
    "  if (!result.ok) return errRes(res, 409, result.error);\n"
    "\n"
    "  // Fetch updated invoice row\n"
    "  const { data: inv } = await supabase\n"
    "    .from('invoices')\n"
    "    .select('id, invoice_number, client_name, amount_total, amount_paid, state, due_date')\n"
    "    .eq('id', invoiceId).single();\n"
    "\n"
    "  // Audit note (non-fatal)\n"
    "  if (body.note) {\n"
    "    const noteContent = 'Payment of Rs ' + amount + ' recorded on ' + (inv ? inv.invoice_number : invoiceId) + '. Note: ' + body.note;\n"
    "    await supabase.from('notes').insert({\n"
    "      vendor_id: vendor.id,\n"
    "      content:   noteContent,\n"
    "      tags:      ['payment', 'invoice'],\n"
    "    });\n"
    "  }\n"
    "\n"
    "  console.log('[invoices:payment] Rs ' + amount + ' on ' + invoiceId + ' -> ' + result.state);\n"
    "  return okRes(res, {\n"
    "    invoice:          inv || null,\n"
    "    payment_recorded: amount,\n"
    "    new_state:        result.state,\n"
    "  });\n"
    "}));\n"
    "\n"
    "// ─── GET /api/v2/vendor/invoices/:invoiceId/pdf ────────────────────────\n"
    "//\n"
    "// Returns the signed Supabase storage URL for the invoice PDF.\n"
    "// Auth: requireAuth. resolveVendor mode C via invoices table.\n"
    "\n"
    "router.get('/:invoiceId/pdf', requireAuth, resolveVendor({ paramName: 'invoiceId', via: 'invoices' }), asyncHandler(async (req, res) => {\n"
    "  const supabase  = req.app.locals.supabase;\n"
    "  const invoiceId = req.params.invoiceId;\n"
    "\n"
    "  const { data: inv } = await supabase\n"
    "    .from('invoices').select('id, pdf_url, invoice_number')\n"
    "    .eq('id', invoiceId).maybeSingle();\n"
    "\n"
    "  if (!inv || !inv.pdf_url) {\n"
    "    return errRes(res, 404, 'PDF not generated yet. Try again in a moment.', 'PDF_PENDING');\n"
    "  }\n"
    "\n"
    "  return okRes(res, { pdf_url: inv.pdf_url, expires_in: 3600 });\n"
    "}));\n"
    "\n"
    "module.exports = router;"
)

content = content.replace(old_cancel, new_handlers, 1)

with open('src/api/vendor/invoices.js', 'w') as f:
    f.write(content)

print('Patched: src/api/vendor/invoices.js')
