import os
os.makedirs('src/lib/vendor', exist_ok=True)

lines = [
    "// src/lib/vendor/clients.js",
    "// Shared write logic for vendor clients.",
    "// Wraps the existing resolveOrCreateClient from src/lib/clients.js.",
    "// Block 1a: adds updateClient, deleteClient (soft), restoreClient.",
    "",
    "'use strict';",
    "",
    "const { resolveOrCreateClient } = require('../clients');",
    "",
    "// ── createClient ─────────────────────────────────────────────────────────",
    "// Idempotent: if phone matches an existing non-deleted client, returns it",
    "// with deduped:true. If phone matches a soft-deleted client, restores it",
    "// and returns deduped:true, restored:true.",
    "",
    "async function createClient(supabase, vendorId, params) {",
    "  const { name, phone, email, notes } = params;",
    "  if (!name || !name.trim()) return { ok: false, error: 'name is required.' };",
    "",
    "  // Check for soft-deleted match on phone first",
    "  if (phone) {",
    "    const { data: deleted } = await supabase",
    "      .from('clients')",
    "      .select('id, name, phone, email, notes, created_at')",
    "      .eq('vendor_id', vendorId)",
    "      .eq('phone', phone)",
    "      .not('deleted_at', 'is', null)",
    "      .maybeSingle();",
    "",
    "    if (deleted) {",
    "      const { data: restored, error: restoreErr } = await supabase",
    "        .from('clients')",
    "        .update({ deleted_at: null, name: name.trim(), email: email || deleted.email, notes: notes || deleted.notes })",
    "        .eq('id', deleted.id)",
    "        .select('id, name, phone, email, notes, created_at')",
    "        .maybeSingle();",
    "      if (restoreErr) return { ok: false, error: restoreErr.message };",
    "      return { ok: true, client: restored, deduped: true, restored: true };",
    "    }",
    "  }",
    "",
    "  // resolveOrCreateClient handles active dedup + insert",
    "  try {",
    "    const { client, created } = await resolveOrCreateClient(supabase, vendorId, {",
    "      name, phone, email, notes, source: 'manual_add',",
    "    });",
    "",
    "    // Back-link any existing leads with matching phone",
    "    if (phone && created) {",
    "      const { data: linked } = await supabase",
    "        .from('leads')",
    "        .update({ client_id: client.id })",
    "        .eq('vendor_id', vendorId)",
    "        .eq('phone', phone)",
    "        .is('client_id', null)",
    "        .select('id');",
    "      if (linked && linked.length > 0) {",
    "        console.log('[clients:create] back-linked ' + linked.length + ' lead(s) to ' + client.id);",
    "      }",
    "    }",
    "",
    "    return { ok: true, client, deduped: !created, restored: false };",
    "  } catch (e) {",
    "    return { ok: false, error: e.message };",
    "  }",
    "}",
    "",
    "// ── updateClient ─────────────────────────────────────────────────────────",
    "// Partial update. Phone update fails with 409 code if it collides with",
    "// another active client for this vendor.",
    "",
    "async function updateClient(supabase, vendorId, clientId, patch) {",
    "  const EDITABLE = ['name', 'phone', 'email', 'notes'];",
    "  const update = {};",
    "  for (const key of EDITABLE) {",
    "    if (patch[key] !== undefined) update[key] = patch[key];",
    "  }",
    "  if (Object.keys(update).length === 0) return { ok: false, error: 'No editable fields provided.' };",
    "",
    "  // Phone collision check",
    "  if (update.phone) {",
    "    const { data: collision } = await supabase",
    "      .from('clients')",
    "      .select('id')",
    "      .eq('vendor_id', vendorId)",
    "      .eq('phone', update.phone)",
    "      .is('deleted_at', null)",
    "      .neq('id', clientId)",
    "      .maybeSingle();",
    "    if (collision) return { ok: false, error: 'Another client uses that phone.', code: 'PHONE_COLLISION' };",
    "  }",
    "",
    "  const { data: client, error } = await supabase",
    "    .from('clients')",
    "    .update(update)",
    "    .eq('id', clientId)",
    "    .eq('vendor_id', vendorId)",
    "    .is('deleted_at', null)",
    "    .select('id, name, phone, email, notes, created_at')",
    "    .maybeSingle();",
    "",
    "  if (!client && !error) return { ok: false, error: 'Client not found.' };",
    "  if (error) return { ok: false, error: error.message };",
    "  return { ok: true, client };",
    "}",
    "",
    "// ── deleteClient ─────────────────────────────────────────────────────────",
    "// Soft delete. leads.client_id and invoices.client_id are NOT nulled --",
    "// those links are kept for history. The client is simply hidden from lists.",
    "",
    "async function deleteClient(supabase, vendorId, clientId) {",
    "  const { data: existing } = await supabase",
    "    .from('clients')",
    "    .select('id, name')",
    "    .eq('id', clientId)",
    "    .eq('vendor_id', vendorId)",
    "    .is('deleted_at', null)",
    "    .maybeSingle();",
    "",
    "  if (!existing) return { ok: false, error: 'Client not found.' };",
    "",
    "  const { error } = await supabase",
    "    .from('clients')",
    "    .update({ deleted_at: new Date().toISOString() })",
    "    .eq('id', clientId)",
    "    .eq('vendor_id', vendorId);",
    "",
    "  if (error) return { ok: false, error: error.message };",
    "  console.log('[clients:delete] soft-deleted ' + clientId + ' (' + existing.name + ')');",
    "  return { ok: true, deleted: true };",
    "}",
    "",
    "module.exports = { createClient, updateClient, deleteClient };",
]

with open('src/lib/vendor/clients.js', 'w') as f:
    f.write('\n'.join(lines) + '\n')

print('Written: src/lib/vendor/clients.js')
