-- repo: dream-os @ 17ea09b10b6e7c43dec37774248c2ea07ef1a848
-- TDW_CE43_AUDIT1_QUERIES.sql — every statement the founder ran in AUDIT-1, 2026-09-16, provenance comments intact.
-- All statements are read-only. Q00 is the chair-issued information_schema witness; Q01-Q13 authored against its pasted result (249 rows); Q14 ruled YES at CE-43 (c-43.2).
-- Founder form: each statement is its own paste block (R-40.31).

-- Q00 witness: information_schema, run by the founder; settles PUBLIC_SCHEMA.md 0154 vs ladder 0166
select table_schema, table_name, column_name, data_type, column_default
from information_schema.columns
where (table_schema, table_name) in (('public','leads'),('public','clients'),('public','events'),('public','invoices'),('public','conversations'),('public','messages'),('public','users'),('public','vendors'),('engine','agents'),('engine','conversations'),('engine','messages'),('engine','facts'),('engine','events'),('engine','leads'),('engine','money_entries'))
order by table_schema, table_name, ordinal_position;

-- Q01 anchor. witness: info_schema paste 2026-09-16 (public.users id,phone,auth_user_id; public.vendors id,user_id,business_name,routing_handle,tier; engine.agents id,user_id,mode,victor_mode,tier) + ENGINE_SCHEMA.md:349-353 (engine.users id,auth_user_id,phone; not in the paste). Bridge per src/engine/src/core/vendorIdentity.ts:24-39.
select pu.id as public_user_id, pu.phone as public_phone, pu.auth_user_id, ve.id as vendor_id, ve.business_name, ve.routing_handle, ve.tier as vendor_tier, eu.id as engine_user_id, eu.phone as engine_phone, ag.id as agent_id, ag.mode as agent_mode, ag.victor_mode, ag.tier as agent_tier from public.users pu left join public.vendors ve on ve.user_id = pu.id left join engine.users eu on eu.auth_user_id = pu.auth_user_id left join engine.agents ag on ag.user_id = eu.id where pu.phone ~ '9888294440$';

-- Q02 counts. witness: info_schema paste (every table's id/agent_id/vendor_id/conversation_id/deleted_at) + ENGINE_SCHEMA.md:349-353 (engine.users).
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id), ec as (select id from engine.conversations where agent_id in (select id from ag)), pc as (select id from public.conversations where vendor_id in (select id from v)) select 'engine.conversations' as tbl, count(*) as total, null::bigint as live from engine.conversations where id in (select id from ec) union all select 'engine.messages', count(*), null from engine.messages where conversation_id in (select id from ec) union all select 'engine.facts', count(*), count(*) filter (where superseded_by is null) from engine.facts where agent_id in (select id from ag) union all select 'engine.events', count(*), null from engine.events where agent_id in (select id from ag) union all select 'engine.money_entries', count(*), null from engine.money_entries where agent_id in (select id from ag) union all select 'engine.leads', count(*), null from engine.leads where agent_id in (select id from ag) union all select 'public.conversations', count(*), null from public.conversations where id in (select id from pc) union all select 'public.messages', count(*), null from public.messages where conversation_id in (select id from pc) union all select 'public.leads', count(*), count(*) filter (where deleted_at is null) from public.leads where vendor_id in (select id from v) union all select 'public.clients', count(*), count(*) filter (where deleted_at is null) from public.clients where vendor_id in (select id from v) union all select 'public.events', count(*), count(*) filter (where deleted_at is null) from public.events where vendor_id in (select id from v) union all select 'public.invoices', count(*), count(*) filter (where deleted_at is null) from public.invoices where vendor_id in (select id from v);

-- Q03 engine.conversations last five. witness: info_schema paste (engine.conversations all 7) + ENGINE_SCHEMA.md:349-353.
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id) select id, agent_id, mode, channel, state, started_at, last_active_at from engine.conversations where agent_id in (select id from ag) order by last_active_at desc limit 5;

-- Q04 engine.messages, one thread (the account's most recently active engine conversation). witness: info_schema paste (engine.messages all 8; engine.conversations id,agent_id,last_active_at) + ENGINE_SCHEMA.md:349-353.
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id), th as (select id from engine.conversations where agent_id in (select id from ag) order by last_active_at desc limit 1) select id, conversation_id, role, content, tool_calls, meta, room, created_at from engine.messages where conversation_id in (select id from th) order by created_at desc limit 5;

-- Q05 engine.facts last five. witness: info_schema paste (engine.facts all 13) + ENGINE_SCHEMA.md:349-353.
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id) select id, agent_id, fact_type, subject, content, verification_status, source_ref, confidence, visibility, scope_contract_id, superseded_by, created_at, updated_at from engine.facts where agent_id in (select id from ag) order by created_at desc limit 5;

-- Q06 engine.events last five. witness: info_schema paste (engine.events all 8) + ENGINE_SCHEMA.md:349-353.
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id) select id, agent_id, actor, action, entity_type, entity_id, summary, created_at from engine.events where agent_id in (select id from ag) order by created_at desc limit 5;

-- Q07 engine.money_entries last five. witness: info_schema paste (engine.money_entries all 15) + ENGINE_SCHEMA.md:349-353.
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id) select id, agent_id, direction, category, amount, counterparty, related_lead_id, related_contract_id, status, verification_status, occurred_at, due_at, visibility, scope_contract_id, created_at from engine.money_entries where agent_id in (select id from ag) order by created_at desc limit 5;

-- Q08 public.conversations last five. witness: info_schema paste (public.conversations all 12; public.users id,phone; public.vendors id,user_id).
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id) select id, vendor_id, counterparty_user_id, counterparty_phone, kind, state, mode, last_message_at, created_at, updated_at, couple_id, prospect_id from public.conversations where vendor_id in (select id from v) order by coalesce(last_message_at, created_at) desc limit 5;

-- Q09 public.messages, one thread: the vendor_self thread. witness: info_schema paste (public.messages all 20; public.conversations id,vendor_id,kind) + PUBLIC_SCHEMA.md:1754-1755 (conversations_kind_check carries 'vendor_self'; 0155-0166 do not touch it). Thread choice per src/agent/engine.js:710-714.
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id), th as (select id from public.conversations where vendor_id in (select id from v) and kind = 'vendor_self') select id, conversation_id, direction, channel, sent_by, body, tool_calls, tool_results, delivery_status, model, message_sid, sender_name, created_at from public.messages where conversation_id in (select id from th) order by created_at desc limit 5;

-- Q10 public.leads last five. witness: info_schema paste (public.leads all 28).
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id) select id, vendor_id, name, phone, email, wedding_date, wedding_date_precision, wedding_city, event_types, functions, function_count, wedding_days, budget_min, budget_max, source, referrer_name, state, client_id, wedding_id, deleted_at, draft_meta, notes, raw_message, vendor_summary, intent_summary, intent_summary_at, created_at, updated_at from public.leads where vendor_id in (select id from v) order by created_at desc limit 5;

-- Q11 public.clients last five. witness: info_schema paste (public.clients all 12).
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id) select id, vendor_id, user_id, name, phone, email, source, referrer_name, notes, deleted_at, created_at, updated_at from public.clients where vendor_id in (select id from v) order by created_at desc limit 5;

-- Q12 public.events last five. witness: info_schema paste (public.events all 18).
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id) select id, vendor_id, title, event_date, event_time, slot, kind, state, linked_lead_id, linked_binder_id, couple_id, ready_by, assigned_member_ids, assigned_circle_member_id, notes, deleted_at, created_at, updated_at from public.events where vendor_id in (select id from v) order by created_at desc limit 5;

-- Q13 public.invoices last five. witness: info_schema paste (public.invoices all 21).
with pu as (select id from public.users where phone ~ '9888294440$'), v as (select ve.id from public.vendors ve join pu on ve.user_id = pu.id) select id, vendor_id, lead_id, client_id, binder_id, invoice_number, client_name, client_phone, description, amount_total, amount_advance, amount_paid, due_date, state, has_schedule, last_payment_at, pdf_url, notes, deleted_at, created_at, updated_at from public.invoices where vendor_id in (select id from v) order by created_at desc limit 5;

-- Q14 engine.records last five plus row e6aacb34 (Dholakia). Ruled YES at CE-43 (c-43.2). witness: ENGINE_SCHEMA.md:310-333 (engine.records all 21; 0155-0166 do not touch it) + ENGINE_SCHEMA.md:349-353 (engine.users) + info_schema paste (public.users id,phone,auth_user_id; engine.agents id,user_id).
with pu as (select id, auth_user_id from public.users where phone ~ '9888294440$'), ag as (select a.id from engine.agents a join engine.users eu on eu.id = a.user_id join pu on pu.auth_user_id = eu.auth_user_id), last5 as (select id from engine.records where agent_id in (select id from ag) order by created_at desc limit 5) select id, agent_id, client, phone, date, stage, amount, direction, amount_received, amount_pending, payment_status, followup_on, followup_note, repeat_every, doc_ref, note, reason_for_action, hidden, hidden_at, created_at, updated_at from engine.records where agent_id in (select id from ag) and (id in (select id from last5) or id = 'e6aacb34-2e05-4729-9be9-7921e09e6f62') order by created_at desc;

