#!/usr/bin/env node
/**
 * b15_schema_register_bench.js — M-SCHEMA-REG, R-34.25/.44. Cures F-SW.7's blind spot.
 *
 * WHAT THIS WATCHES, AND WHY NOTHING WATCHED IT BEFORE.
 * docs/db/PUBLIC_SCHEMA.md is written by a PAIR of scripts that each rewrite the
 * other's leftovers. format_public_schema.js keeps ONLY the sentinel-onward tail
 * of the existing file; append_constraints_to_public_schema.js keeps ONLY the head
 * above the sentinel. Every byte of that document therefore belongs to exactly one
 * generator and is destroyed by the other's run.
 *
 * For the whole life of the document nothing anywhere in either repo executed
 * either script (grep -rln across scripts/ in dream-os and dreamos-pwa: zero).
 * That is the root cause of F-SW.7: F-SW.3's standing cure was hand-authored into
 * the head region, the head region is regenerated by the formatter, and the cure
 * self-deleted from the day it was written. Nobody noticed because no test ever
 * ran the pipe and looked at what came out the far side.
 *
 * THE ASSERTION IS DELIBERATELY END-TO-END. Unit-testing the renderer would have
 * caught nothing: the old cure's problem was never that it rendered wrong, it was
 * that a DIFFERENT script deleted it afterwards. So this cell runs the real pipe,
 * both halves, in order, and reads the file that survives.
 *
 * ISOLATION IS BY TEMP TREE, NOT TEMP FILE, AND THAT IS FORCED.
 * append_constraints_to_public_schema.js:64 resolves its TARGET off __dirname —
 * `path.resolve(__dirname, '..', '..', 'docs/db/PUBLIC_SCHEMA.md')` — with no argv
 * override. There is no way to point it at a scratch file. So the whole relevant
 * subtree is copied to os.tmpdir() and the scripts are run from inside the copy,
 * where their own __dirname carries them to the copy's doc. db/migrations/ travels
 * in that copy because the ladder derivation (:137) and both register aborts read
 * it off __dirname too; without it the run would abort for the wrong reason and
 * the cell would report a false red.
 *
 * NO LIVE DUMP IS TOUCHED (R-34.26). Both halves are fed fixture CSVs built here.
 *
 * Run:  node scripts/b15_schema_register_bench.js
 * Exit: 0 green · 1 red.
 */
'use strict';
const fs   = require('fs');
const os   = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const REPO = path.resolve(__dirname, '..');
const SNAP = '2026-08-13';
const TIP  = '0123';
const REPO_TIP = 'benchfixture';

let tmp = null;
const fail = m => { console.error('  RED  ' + m); process.exitCode = 1; };

function csv(rows) { return rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n') + '\n'; }

function buildTree() {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'b15-schema-register-'));
  fs.mkdirSync(path.join(tmp, 'db', 'queries'), { recursive: true });
  fs.mkdirSync(path.join(tmp, 'docs', 'db'),    { recursive: true });
  for (const f of fs.readdirSync(path.join(REPO, 'db', 'queries')))
    if (f.endsWith('.js'))
      fs.copyFileSync(path.join(REPO, 'db', 'queries', f), path.join(tmp, 'db', 'queries', f));
  // The migrations directory travels whole: the ladder, the filename derivation and
  // the file-exists abort all read it. A subset would change what the pipe computes.
  fs.cpSync(path.join(REPO, 'db', 'migrations'), path.join(tmp, 'db', 'migrations'), { recursive: true });
  fs.copyFileSync(path.join(REPO, 'docs', 'db', 'PUBLIC_SCHEMA.md'), path.join(tmp, 'docs', 'db', 'PUBLIC_SCHEMA.md'));

  const fx = path.join(tmp, 'fx');
  fs.mkdirSync(fx);
  fs.writeFileSync(path.join(fx, 'cols.csv'), csv([
    ['tables_expected', 'table_name', 'columns', 'columns_detail'],
    ['2', 'bench_alpha', '2', '1. id uuid NOT NULL\n2. name text NOT NULL'],
    ['2', 'bench_beta',  '1', '1. id uuid NOT NULL'],
  ]));
  fs.writeFileSync(path.join(fx, 's1.csv'), csv([
    ['rows_expected', 'table_name', 'constraint_type', 'constraint_name', 'definition'],
    ['1', 'bench_alpha', 'PRIMARY KEY', 'bench_alpha_pkey', 'PRIMARY KEY (id)'],
  ]));
  fs.writeFileSync(path.join(fx, 's2.csv'), csv([
    ['rows_expected', 'table_name', 'constraint_name', 'definition'],
    ['1', 'bench_beta', 'bench_beta_alpha_fk', 'FOREIGN KEY (id) REFERENCES bench_alpha(id)'],
  ]));
  fs.writeFileSync(path.join(fx, 's3.csv'), csv([
    ['rows_expected', 'table_name', 'index_name', 'definition'],
    ['1', 'bench_alpha', 'bench_alpha_pkey', 'CREATE UNIQUE INDEX bench_alpha_pkey ON public.bench_alpha USING btree (id)'],
  ]));
  return { fx, doc: path.join(tmp, 'docs', 'db', 'PUBLIC_SCHEMA.md') };
}

function runPipe(fx, doc) {
  const opts = { cwd: tmp, encoding: 'utf8', stdio: 'pipe' };
  execFileSync('node', [path.join(tmp, 'db', 'queries', 'format_public_schema.js'),
    path.join(fx, 'cols.csv'), doc, SNAP, TIP, REPO_TIP], opts);
  execFileSync('node', [path.join(tmp, 'db', 'queries', 'append_constraints_to_public_schema.js'),
    path.join(fx, 's1.csv'), path.join(fx, 's2.csv'), path.join(fx, 's3.csv'), SNAP, TIP, REPO_TIP], opts);
  return fs.readFileSync(doc, 'utf8');
}

function main() {
  console.log('\n== b15 · THE OUT-OF-ORDER REGISTER SURVIVES ITS OWN GENERATOR ==\n');
  const reg = JSON.parse(fs.readFileSync(path.join(REPO, 'db', 'migrations', 'OUT_OF_ORDER.json'), 'utf8')).register;
  // (R-34.47) THE EMPTY REGISTER IS THE GOAL STATE, NOT A BROKEN ONE.
  // This cell used to REFUSE to run when the register held no records, on the
  // reasoning that carriage of nothing cannot be proven. That was defensible for
  // the two seeded rows and wrong as a general rule: a register empties when every
  // recorded debt has been paid by a regen, which is the state the estate is
  // supposed to reach. The bench would have gone red on a correct tree the first
  // time it got there — and the first time was the run immediately after F-SW.7's
  // own closure, which is as bad a moment to cry wolf as exists.
  //
  // It also left the renderer's empty branch (:285) as the only path nothing had
  // ever executed. So the empty state now gets asserted rather than refused: the
  // warning paragraph must STILL survive — a reader needs to know the blind spot
  // exists and where to record the next migration, whether or not anything is
  // outstanding today — and the empty-state line must render in place of the table.
  const EMPTY = !reg.length;
  if (EMPTY) console.log('  ..   register is empty (all debts paid) — asserting the empty state');

  const { fx, doc } = buildTree();
  const before = fs.readFileSync(doc, 'utf8');
  const after  = runPipe(fx, doc);

  // ── 1. THE WARNING PARAGRAPH. The reader's only notice that the arithmetic
  //       staleness test has a blind spot. It was hand-authored and as doomed as
  //       the rows; if this assertion fails the register may still be present and
  //       nobody will know to read it.
  // Anchored on the paragraph's STABLE prefix, deliberately stopping before the
  // clause R-34.45(ii) re-pointed. The survival assertion must outlive legitimate
  // amendments to the instruction; anchoring on wording that is expected to change
  // makes this cell red on correct work, which trains the next seat to ignore it.
  const WARN = '\u26a0 THE RULE ABOVE HAS A BLIND SPOT, AND EVERY MIGRATION THAT ENTERS IT MUST NAME ITSELF';
  if (!before.includes(WARN)) fail('fixture doc did not carry the warning paragraph in — bench tree is wrong, not the code.');
  if (!after.includes(WARN))  fail('the warning paragraph did NOT survive the pipe.');
  else console.log('  ok   warning paragraph survives both halves');

  // ── 2. THE TABLE HEADER.
  const HEAD = '| out-of-order migration | tables it makes this document STALE for | state |';
  const EMPTY_LINE = '_No out-of-order migration is outstanding at this snapshot._';
  if (EMPTY) {
    // The table must be ABSENT, not merely empty: a header with no rows under it
    // reads as data lost in transit rather than as a debt-free ladder.
    if (!after.includes(EMPTY_LINE)) fail('the empty-state line did NOT render in place of the table.');
    else if (after.includes(HEAD)) fail('an empty register still rendered a table header with no rows beneath it.');
    else console.log('  ok   empty state renders its own line, no orphan table header');
  } else if (!after.includes(HEAD)) fail('the register table header did NOT survive the pipe.');
  else console.log('  ok   table header survives both halves');

  // ── 3. EVERY ROW, RENDERED FROM THE COMMITTED INPUT, byte-compared against the
  //       cell this bench builds from that same input. Presence is not enough: a
  //       row that survives with the wrong column count is worse than an absent
  //       one, because the reader trusts it.
  const ladder = fs.readdirSync(path.join(REPO, 'db', 'migrations')).filter(f => f.endsWith('.sql'));
  if (EMPTY && !after.includes('| `0')) console.log('  ok   no register rows rendered, correctly');
  for (const r of reg) {
    const file = ladder.find(f => f.startsWith(String(r.number).padStart(4, '0') + '_'));
    if (!file) { fail(`register names ${r.number} but no .sql matches it in db/migrations/`); continue; }
    const row = `| \`${file}\` (${r.note}) | ${r.stale_for} | ${r.state} |`;
    if (!after.includes(row)) fail(`row for ${file} did not survive the pipe intact.\n       expected: ${row}`);
    else console.log(`  ok   row survives intact · ${file}`);
  }

  // ── 4. ORDER IS HISTORY, not numeric. If the renderer ever starts sorting, the
  //       document silently reorders and a reader's sense of "what came last" goes
  //       with it. Assert the input's own order came out the far side.
  const pos = EMPTY ? [] : reg.map(r => {
    const file = ladder.find(f => f.startsWith(String(r.number).padStart(4, '0') + '_'));
    return after.indexOf('`' + file + '`');
  });
  if (EMPTY) { /* order is vacuous with no rows */ }
  else if (pos.some(p => p < 0) || pos.some((p, i) => i && p < pos[i - 1]))
    fail('register rows did not survive in input order.');
  else console.log('  ok   rows survive in input order, not sorted');

  // ── 5. THE REGION IS SINGLE-HOMED. One home per byte: if the renderer emits the
  //       warning twice — say a future hand-edit reintroduces the old prose above
  //       it — the document acquires two warnings that can drift apart.
  const n = after.split(WARN).length - 1;
  if (n !== 1) fail(`the warning paragraph appears ${n} times; exactly one home is required.`);
  else console.log('  ok   exactly one home for the warning paragraph');

  // ── 6. THE SENTINEL SURVIVED AND THE ADDENDUM IS BELOW IT — proof the pipe ran
  //       whole rather than the formatter alone leaving a half-written file.
  if (!after.includes('<!-- CONSTRAINTS-ADDENDUM:BEGIN') || !after.includes('<!-- CONSTRAINTS-ADDENDUM:END -->'))
    fail('the constraints addendum is not intact — the second half of the pipe did not complete.');
  else console.log('  ok   addendum intact below the sentinel');

  // ══ (R-34.46) THE PARAGRAPH'S TWO CLAIMS ═════════════════════════════════
  // The paragraph shipped as a "byte-unchanged copy move" and carried two claims
  // that the same delivery falsified: a TYPED count sitting one line under a
  // DERIVED one, and an instruction pointing migration authors at the header —
  // the regenerated region — rather than at OUT_OF_ORDER.json. Neither was caught
  // by anything, because nothing asserted on the paragraph's CONTENT, only its
  // presence. These cells assert content.

  const para = (after.match(/\*\*\u26a0 THE RULE ABOVE HAS A BLIND SPOT[^\n]*/) || [''])[0];
  if (!para) fail('could not isolate the warning paragraph to inspect its claims.');

  // ── 7. THE INSTRUCTION POINTS AT THE REGISTER, NOT AT THIS HEADER.
  if (!para.includes('db/migrations/OUT_OF_ORDER.json'))
    fail('the warning paragraph does not name OUT_OF_ORDER.json — it is still pointing authors somewhere else.');
  else if (/ships its own line into this header/.test(para))
    fail('the warning paragraph still carries the retired instruction to hand-edit this header.');
  else console.log('  ok   instruction points at OUT_OF_ORDER.json, not at this header');

  // ── 8. THE COUNT IS DERIVED, PROVEN BY MOVING THE TREE UNDER IT.
  // Presence of a correct number proves nothing — a typed number is correct until
  // the directory changes. So FILL A HOLE in the temp tree and re-run the pipe:
  // a derived count follows, a typed one does not. The mutation is production
  // code's own input, and it lives and dies inside the temp tree.
  const claimed = (para.match(/holds (\d+) reserved-but-empty/) || [])[1];
  if (claimed === undefined) fail('the warning paragraph states no count at all.');
  else {
    const migDir = path.join(tmp, 'db', 'migrations');
    const absent = (() => {
      const ns = fs.readdirSync(migDir).filter(f => /^\d{4}_.*\.sql$/.test(f)).map(f => Number(f.slice(0, 4))).sort((a, b) => a - b);
      const have = new Set(ns);
      const arc = new Set(fs.existsSync(path.join(migDir, 'archive'))
        ? fs.readdirSync(path.join(migDir, 'archive')).filter(f => /^\d{4}_/.test(f)).map(f => Number(f.slice(0, 4))) : []);
      const out = [];
      for (let i = ns[0]; i <= ns[ns.length - 1]; i++) if (!have.has(i) && !arc.has(i)) out.push(i);
      return out;
    })();
    if (Number(claimed) !== absent.length)
      fail(`the paragraph claims ${claimed} reserved-but-empty numbers; the directory holds ${absent.length}.`);
    else {
      const fill = String(absent[0]).padStart(4, '0') + '_bench_fill.sql';
      fs.writeFileSync(path.join(migDir, fill), '-- bench fixture, temp tree only\n');
      const para2 = (runPipe(fx, doc).match(/\*\*\u26a0 THE RULE ABOVE HAS A BLIND SPOT[^\n]*/) || [''])[0];
      const claimed2 = (para2.match(/holds (\d+) reserved-but-empty/) || [])[1];
      fs.unlinkSync(path.join(migDir, fill));
      if (Number(claimed2) !== absent.length - 1)
        fail(`the count did not follow the directory: filled hole ${fill}, expected ${absent.length - 1}, paragraph said ${claimed2}. It is TYPED, not derived.`);
      else console.log(`  ok   count is derived — followed the tree ${absent.length} → ${claimed2} when a hole was filled`);
    }
  }

  console.log(process.exitCode ? '\n  RED\n' : '\n  GREEN — the register survives its own generator.\n');
}

try { main(); }
catch (e) { console.error('  RED  bench threw: ' + (e.stderr || e.message)); process.exitCode = 2 /* F-39.67: an unexpected throw is an ERROR, never a FAIL */; }
finally { if (tmp) fs.rmSync(tmp, { recursive: true, force: true }); }
