#!/usr/bin/env node
/**
 * b15_schema_register_bench.js — M-SCHEMA-REG, R-34.25/.44. Cures F-SW.7's blind spot.
 *
 * WHAT THIS WATCHES, AND WHY NOTHING WATCHED IT BEFORE.
 * docs/db/PUBLIC_SCHEMA.md is written by a PAIR of scripts that each rewrite the
 * other's leftovers. format_public_schema.js keeps ONLY the sentinel-onward tail
 * of the existing file; append_constraints_to_public_schema.js keeps ONLY the head
 * above the sentinel. Every byte of that document therefore belongs to exactly one
 * generator and is destroyed by the other's run.
 *
 * For the whole life of the document nothing anywhere in either repo executed
 * either script (grep -rln across scripts/ in dream-os and dreamos-pwa: zero).
 * That is the root cause of F-SW.7: F-SW.3's standing cure was hand-authored into
 * the head region, the head region is regenerated by the formatter, and the cure
 * self-deleted from the day it was written. Nobody noticed because no test ever
 * ran the pipe and looked at what came out the far side.
 *
 * THE ASSERTION IS DELIBERATELY END-TO-END. Unit-testing the renderer would have
 * caught nothing: the old cure's problem was never that it rendered wrong, it was
 * that a DIFFERENT script deleted it afterwards. So this cell runs the real pipe,
 * both halves, in order, and reads the file that survives.
 *
 * ISOLATION IS BY TEMP TREE, NOT TEMP FILE, AND THAT IS FORCED.
 * append_constraints_to_public_schema.js:64 resolves its TARGET off __dirname —
 * `path.resolve(__dirname, '..', '..', 'docs/db/PUBLIC_SCHEMA.md')` — with no argv
 * override. There is no way to point it at a scratch file. So the whole relevant
 * subtree is copied to os.tmpdir() and the scripts are run from inside the copy,
 * where their own __dirname carries them to the copy's doc. db/migrations/ travels
 * in that copy because the ladder derivation (:137) and both register aborts read
 * it off __dirname too; without it the run would abort for the wrong reason and
 * the cell would report a false red.
 *
 * NO LIVE DUMP IS TOUCHED (R-34.26). Both halves are fed fixture CSVs built here.
 *
 * Run:  node scripts/b15_schema_register_bench.js
 * Exit: 0 green · 1 red.
 */
'use strict';
const fs   = require('fs');
const os   = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const REPO = path.resolve(__dirname, '..');
const SNAP = '2026-08-13';
const TIP  = '0123';
const REPO_TIP = 'benchfixture';

let tmp = null;
const fail = m => { console.error('  RED  ' + m); process.exitCode = 1; };

function csv(rows) { return rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n') + '\n'; }

function buildTree() {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'b15-schema-register-'));
  fs.mkdirSync(path.join(tmp, 'db', 'queries'), { recursive: true });
  fs.mkdirSync(path.join(tmp, 'docs', 'db'),    { recursive: true });
  for (const f of fs.readdirSync(path.join(REPO, 'db', 'queries')))
    if (f.endsWith('.js'))
      fs.copyFileSync(path.join(REPO, 'db', 'queries', f), path.join(tmp, 'db', 'queries', f));
  // The migrations directory travels whole: the ladder, the filename derivation and
  // the file-exists abort all read it. A subset would change what the pipe computes.
  fs.cpSync(path.join(REPO, 'db', 'migrations'), path.join(tmp, 'db', 'migrations'), { recursive: true });
  fs.copyFileSync(path.join(REPO, 'docs', 'db', 'PUBLIC_SCHEMA.md'), path.join(tmp, 'docs', 'db', 'PUBLIC_SCHEMA.md'));

  const fx = path.join(tmp, 'fx');
  fs.mkdirSync(fx);
  fs.writeFileSync(path.join(fx, 'cols.csv'), csv([
    ['tables_expected', 'table_name', 'columns', 'columns_detail'],
    ['2', 'bench_alpha', '2', '1. id uuid NOT NULL\n2. name text NOT NULL'],
    ['2', 'bench_beta',  '1', '1. id uuid NOT NULL'],
  ]));
  fs.writeFileSync(path.join(fx, 's1.csv'), csv([
    ['rows_expected', 'table_name', 'constraint_type', 'constraint_name', 'definition'],
    ['1', 'bench_alpha', 'PRIMARY KEY', 'bench_alpha_pkey', 'PRIMARY KEY (id)'],
  ]));
  fs.writeFileSync(path.join(fx, 's2.csv'), csv([
    ['rows_expected', 'table_name', 'constraint_name', 'definition'],
    ['1', 'bench_beta', 'bench_beta_alpha_fk', 'FOREIGN KEY (id) REFERENCES bench_alpha(id)'],
  ]));
  fs.writeFileSync(path.join(fx, 's3.csv'), csv([
    ['rows_expected', 'table_name', 'index_name', 'definition'],
    ['1', 'bench_alpha', 'bench_alpha_pkey', 'CREATE UNIQUE INDEX bench_alpha_pkey ON public.bench_alpha USING btree (id)'],
  ]));
  return { fx, doc: path.join(tmp, 'docs', 'db', 'PUBLIC_SCHEMA.md') };
}

function runPipe(fx, doc) {
  const opts = { cwd: tmp, encoding: 'utf8', stdio: 'pipe' };
  execFileSync('node', [path.join(tmp, 'db', 'queries', 'format_public_schema.js'),
    path.join(fx, 'cols.csv'), doc, SNAP, TIP, REPO_TIP], opts);
  execFileSync('node', [path.join(tmp, 'db', 'queries', 'append_constraints_to_public_schema.js'),
    path.join(fx, 's1.csv'), path.join(fx, 's2.csv'), path.join(fx, 's3.csv'), SNAP, TIP, REPO_TIP], opts);
  return fs.readFileSync(doc, 'utf8');
}

function main() {
  console.log('\n== b15 · THE OUT-OF-ORDER REGISTER SURVIVES ITS OWN GENERATOR ==\n');
  const reg = JSON.parse(fs.readFileSync(path.join(REPO, 'db', 'migrations', 'OUT_OF_ORDER.json'), 'utf8')).register;
  if (!reg.length) return fail('OUT_OF_ORDER.json holds no records — this cell cannot prove carriage of nothing.');

  const { fx, doc } = buildTree();
  const before = fs.readFileSync(doc, 'utf8');
  const after  = runPipe(fx, doc);

  // ── 1. THE WARNING PARAGRAPH. The reader's only notice that the arithmetic
  //       staleness test has a blind spot. It was hand-authored and as doomed as
  //       the rows; if this assertion fails the register may still be present and
  //       nobody will know to read it.
  const WARN = 'THE RULE ABOVE HAS A BLIND SPOT, AND EVERY MIGRATION THAT ENTERS IT MUST NAME ITSELF HERE (F-SW.3, ruled CE-32).';
  if (!before.includes(WARN)) fail('fixture doc did not carry the warning paragraph in — bench tree is wrong, not the code.');
  if (!after.includes(WARN))  fail('the warning paragraph did NOT survive the pipe.');
  else console.log('  ok   warning paragraph survives both halves');

  // ── 2. THE TABLE HEADER.
  const HEAD = '| out-of-order migration | tables it makes this document STALE for | state |';
  if (!after.includes(HEAD)) fail('the register table header did NOT survive the pipe.');
  else console.log('  ok   table header survives both halves');

  // ── 3. EVERY ROW, RENDERED FROM THE COMMITTED INPUT, byte-compared against the
  //       cell this bench builds from that same input. Presence is not enough: a
  //       row that survives with the wrong column count is worse than an absent
  //       one, because the reader trusts it.
  const ladder = fs.readdirSync(path.join(REPO, 'db', 'migrations')).filter(f => f.endsWith('.sql'));
  for (const r of reg) {
    const file = ladder.find(f => f.startsWith(String(r.number).padStart(4, '0') + '_'));
    if (!file) { fail(`register names ${r.number} but no .sql matches it in db/migrations/`); continue; }
    const row = `| \`${file}\` (${r.note}) | ${r.stale_for} | ${r.state} |`;
    if (!after.includes(row)) fail(`row for ${file} did not survive the pipe intact.\n       expected: ${row}`);
    else console.log(`  ok   row survives intact · ${file}`);
  }

  // ── 4. ORDER IS HISTORY, not numeric. If the renderer ever starts sorting, the
  //       document silently reorders and a reader's sense of "what came last" goes
  //       with it. Assert the input's own order came out the far side.
  const pos = reg.map(r => {
    const file = ladder.find(f => f.startsWith(String(r.number).padStart(4, '0') + '_'));
    return after.indexOf('`' + file + '`');
  });
  if (pos.some(p => p < 0) || pos.some((p, i) => i && p < pos[i - 1]))
    fail('register rows did not survive in input order.');
  else console.log('  ok   rows survive in input order, not sorted');

  // ── 5. THE REGION IS SINGLE-HOMED. One home per byte: if the renderer emits the
  //       warning twice — say a future hand-edit reintroduces the old prose above
  //       it — the document acquires two warnings that can drift apart.
  const n = after.split(WARN).length - 1;
  if (n !== 1) fail(`the warning paragraph appears ${n} times; exactly one home is required.`);
  else console.log('  ok   exactly one home for the warning paragraph');

  // ── 6. THE SENTINEL SURVIVED AND THE ADDENDUM IS BELOW IT — proof the pipe ran
  //       whole rather than the formatter alone leaving a half-written file.
  if (!after.includes('<!-- CONSTRAINTS-ADDENDUM:BEGIN') || !after.includes('<!-- CONSTRAINTS-ADDENDUM:END -->'))
    fail('the constraints addendum is not intact — the second half of the pipe did not complete.');
  else console.log('  ok   addendum intact below the sentinel');

  console.log(process.exitCode ? '\n  RED\n' : '\n  GREEN — the register survives its own generator.\n');
}

try { main(); }
catch (e) { console.error('  RED  bench threw: ' + (e.stderr || e.message)); process.exitCode = 1; }
finally { if (tmp) fs.rmSync(tmp, { recursive: true, force: true }); }
