#!/usr/bin/env node
// ════════════════════════════════════════════════════════════════════
// db/queries/append_constraints_to_public_schema.js
//
// The generator for public_constraints_dump.sql's output. TDW_04 Part B, the
// CHECKER sitting. CE-ruled 2026-07-16.
//
// ── WHY A SCRIPT AND NOT FINGERS ────────────────────────────────────────
//
// docs/db/PUBLIC_SCHEMA.md's own header carries the law:
//
//     NEVER HAND-EDIT. A hand-edited snapshot is prose again, and prose is what
//     this file exists to kill.
//
// That law has no enforcement. It is a sentence in a file asking to be obeyed —
// and F-04.57 is the finding about exactly what happens when a schema fact travels
// through a human's short-term memory instead of a pipe. So the addendum enters
// THROUGH THIS FILE OR IT DOES NOT ENTER. The law is kept by construction rather
// than by good intentions.
//
//   node db/queries/append_constraints_to_public_schema.js s1.csv s2.csv s3.csv
//
// ── WHAT IT REFUSES TO DO, AND THIS IS THE POINT ────────────────────────
//
// IT WILL NOT APPEND A CAPPED RESULT. Every section carries a self-computing
// `rows_expected` — a scalar subquery the database evaluates and repeats on every
// row, structurally immune to the editor's row cap. If rows_returned < rows_expected
// the cap bit, and this script EXITS NONZERO WITHOUT WRITING.
//
// That check is here rather than in a comment because of what a capped constraints
// list actually is: it reports ABSENCE where there is only TRUNCATION. And absence
// is the fact this addendum exists to establish — `vendors.slot_capacity` having no
// CHECK is Q-SP-1's ruling, and a truncated §1 would "confirm" it by saying nothing.
// F-04.29 is the founding case: the engine dump's first run was silently cut to 99
// rows, dropping 12 tables including the two the whole defect class was about, and
// nobody noticed. **A reference that silently returns a PARTIAL truth is the disease
// it was built to cure.**
//
// ── IDEMPOTENT BY SENTINEL ──────────────────────────────────────────────
//
// Re-running replaces the addendum rather than stacking a second one. The sentinel
// below is the seam. Everything above it is the column snapshot and is NEVER touched
// by this script — it is public_schema_dump.sql's output and belongs to that file.
//
// ── WHAT IS NOT COMMITTED, NAMED ────────────────────────────────────────
//
// The three CSVs are NOT committed, following this file's sibling exactly:
// public_schema_dump.sql's output lives in PUBLIC_SCHEMA.md and its raw result set
// lives nowhere. The re-run path is the SQL, not the CSV — which is why the SQL is
// the committed artifact and is founder-runnable on demand (Q-SP-5). Committing the
// CSVs would create a second home for the same facts, one of which would go stale
// silently. F-04.36's shape, in a docs directory.
// ════════════════════════════════════════════════════════════════════
'use strict';

const fs   = require('fs');
const path = require('path');

const TARGET   = path.resolve(__dirname, '..', '..', 'docs/db/PUBLIC_SCHEMA.md');
const SENTINEL = '<!-- CONSTRAINTS-ADDENDUM:BEGIN — generated by db/queries/append_constraints_to_public_schema.js. Everything below this line is script-written. Do not hand-edit. -->';

// ── a CSV parser that handles quoted fields with embedded newlines ────────
// Written rather than depended on: pg_get_constraintdef and indexdef both emit
// commas and quotes inside their values, and a split(',') would shred them into
// silently wrong columns. This is the one place a lazy parse would corrupt the
// witnessed facts and still look green.
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1 || (r.length === 1 && r[0] !== ''));
}

function load(file, label) {
  if (!fs.existsSync(file)) { console.error(`ABORT — ${label}: no such file: ${file}`); process.exit(2); }
  const rows = parseCSV(fs.readFileSync(file, 'utf8'));
  const head = rows.shift();
  if (!head || head[0] !== 'rows_expected') {
    console.error(`ABORT — ${label}: first column is not \`rows_expected\` (got ${JSON.stringify(head && head[0])}).`);
    console.error(`         This file was not produced by public_constraints_dump.sql. The guard IS the first column;`);
    console.error(`         a result set without it cannot be checked and must not be appended.`);
    process.exit(2);
  }
  const objs = rows.map(r => Object.fromEntries(head.map((h, i) => [h, r[i] === undefined ? '' : r[i]])));

  // ── THE GUARD. Enforced, not documented. ──
  const expectedSet = new Set(objs.map(o => o.rows_expected));
  if (expectedSet.size !== 1) {
    console.error(`ABORT — ${label}: rows_expected is not constant across rows (${[...expectedSet].join(', ')}).`);
    console.error(`         It is a scalar subquery and MUST be identical on every row. This result set is malformed.`);
    process.exit(2);
  }
  const expected = parseInt([...expectedSet][0], 10);
  const got = objs.length;
  if (got !== expected) {
    console.error(`ABORT — ${label}: THE CAP BIT. rows_returned=${got}, rows_expected=${expected}.`);
    console.error(`         Raise the SQL editor's Limit and re-run. NOTHING WAS WRITTEN.`);
    console.error(`         A capped constraints list reports ABSENCE where there is only TRUNCATION,`);
    console.error(`         and absence is the fact this addendum exists to establish.`);
    process.exit(1);
  }
  console.log(`  GUARD PASS  ${label.padEnd(22)} rows_returned=${got} == rows_expected=${expected}`);
  return objs;
}

// ── emit ─────────────────────────────────────────────────────────────────
function esc(s) { return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' '); }

function byTable(rows, render) {
  const groups = new Map();
  for (const r of rows) { if (!groups.has(r.table_name)) groups.set(r.table_name, []); groups.get(r.table_name).push(r); }
  let out = '';
  for (const t of [...groups.keys()].sort()) {
    out += `\n### public.${t}\n\n`;
    out += '```\n' + groups.get(t).map(render).join('\n') + '\n```\n';
  }
  return out;
}

function main() {
  const [f1, f2, f3] = process.argv.slice(2);
  if (!f1 || !f2 || !f3) {
    console.error('usage: node db/queries/append_constraints_to_public_schema.js <§1.csv> <§2.csv> <§3.csv>');
    console.error('  §1 = CHECK/UNIQUE/PK   §2 = FOREIGN KEYS   §3 = INDEXES');
    process.exit(2);
  }
  console.log('\n== THE GUARD — rows_expected is computed by the DATABASE and cannot be capped ==\n');
  const s1 = load(f1, '§1 CHECK/UNIQUE/PK');
  const s2 = load(f2, '§2 FOREIGN KEYS');
  const s3 = load(f3, '§3 INDEXES');
  console.log('\n  ALL THREE COMPLETE — nothing was truncated.\n');

  const stamp = new Date().toISOString().slice(0, 10);
  let md = SENTINEL + '\n\n---\n\n';
  md += `# CONSTRAINTS ADDENDUM — what the \`public\` schema REFUSES\n\n`;
  md += `**Snapshot taken:** 2026-07-16, founder-run in the Supabase SQL editor, output handed back verbatim.\n`;
  md += `**Project / role:** \`nvzkbagqxbysoeszxent\` / \`main\` (PRODUCTION), role \`postgres\`.\n`;
  md += `**Generated by:** \`db/queries/append_constraints_to_public_schema.js\` from \`db/queries/public_constraints_dump.sql\`'s three sections. **Regenerate on demand by re-running both.**\n`;
  md += `**NEVER HAND-EDIT.** The generator refuses a capped result and refuses a result set without its guard column; hand-editing routes around both.\n\n`;
  md += `**THE GUARD PASSED, ALL THREE SECTIONS.** §1 **${s1.length}/${s1[0].rows_expected}** · §2 **${s2.length}/${s2[0].rows_expected}** · §3 **${s3.length}/${s3[0].rows_expected}**. Rows returned == \`rows_expected\` ⇒ the editor's row cap did not truncate. (F-04.29's disease, made self-detecting. The engine twin hardcodes *"confirm 25 rows"*; these cannot, because the counts are the facts they exist to establish.)\n\n`;
  md += `**WHY THIS ADDENDUM EXISTS.** The column snapshot above answers *"what columns exist, of what type."* It is drawn from \`information_schema.columns\`, which yields name, type, nullability and default — **and nothing else.** It does not answer ***"what values are legal."*** That file's own scope note names the gap: \`events.kind\`'s CHECK, \`events.slot\`'s CHECK and \`0075\`'s UNIQUE partial index were **real and invisible** there. The occupancy checker rides on all three. *Founder-run SQL is written ONLY against witnessed lists — and a constraint is a fact about the schema exactly as much as a column is.*\n\n`;
  md += `**SCOPE, so the silence is not misread.** Schema \`public\`, BASE TABLEs only — matching the column snapshot exactly. §1 covers CHECK, UNIQUE and PRIMARY KEY. §2 covers FOREIGN KEYs with their referenced table and delete rule. §3 covers indexes **including partial ones**. **TRIGGERS AND RLS POLICIES ARE ABSENT AND THAT IS DELIBERATE** — no ruling needs them, and a silent widening of a witnessed reference is how a reference stops being trustworthy.\n\n`;
  md += `**⚠ A CONSTRAINT READ WITHOUT ITS PREDICATE IS A CONSTRAINT MISREAD.** \`events_vendor_date_blocked_unique_idx\` is UNIQUE on \`(vendor_id, event_date)\` **WHERE \`kind = 'blocked' AND deleted_at IS NULL\`**. The predicate lives inside \`indexdef\` and nowhere else. Read without it, it appears to forbid a vendor two events on one day — catastrophic and false. **This is why §3 exists as its own section instead of being folded into §1.**\n\n`;
  md += `---\n\n## §1 — CHECK / UNIQUE / PRIMARY KEY  ·  ${s1.length} constraints\n`;
  md += byTable(s1, r => `[${r.constraint_type}] ${r.constraint_name}\n    ${esc(r.definition)}`);
  md += `\n---\n\n## §2 — FOREIGN KEYS  ·  ${s2.length} constraints\n`;
  md += byTable(s2, r => `${r.constraint_name}\n    ${esc(r.definition)}`);
  md += `\n---\n\n## §3 — INDEXES  ·  ${s3.length} indexes\n`;
  md += byTable(s3, r => `${r.index_name}\n    ${esc(r.definition)}`);
  md += `\n<!-- CONSTRAINTS-ADDENDUM:END -->\n`;

  const existing = fs.readFileSync(TARGET, 'utf8');
  const cut = existing.indexOf(SENTINEL);
  const head = cut === -1 ? existing.replace(/\s*$/, '\n\n') : existing.slice(0, cut);
  fs.writeFileSync(TARGET, head + md);
  console.log(`  ${cut === -1 ? 'APPENDED' : 'REPLACED'} the addendum in ${path.relative(process.cwd(), TARGET)}`);
  console.log(`  §1 ${s1.length} · §2 ${s2.length} · §3 ${s3.length}\n`);
}

main();
