#!/usr/bin/env node
// ════════════════════════════════════════════════════════════════════
// db/queries/format_public_schema.js
//
// The generator for public_schema_dump.sql's output — the COLUMN-SNAPSHOT half
// of docs/db/PUBLIC_SCHEMA.md. Twin of append_constraints_to_public_schema.js,
// which owns the CONSTRAINTS ADDENDUM half below the sentinel.
// TDW_05 P4, CE-63 (2026-07-23).
//
// ── WHY THIS FILE EXISTS ────────────────────────────────────────────────
//
// docs/db/PUBLIC_SCHEMA.md's own header carries the law:
//
//     NEVER HAND-EDIT. A hand-edited snapshot is prose again, and prose is what
//     this file exists to kill.
//
// Until this file, that law was HALF-ENFORCED. The constraints addendum had a
// committed generator and could only enter through it. The column snapshot had
// none — so the half of the document that answers "what columns exist, of what
// type" entered by whatever means the sitting improvised, and the law protecting
// it was a sentence asking to be obeyed.
//
// That asymmetry is the same shape as the finding this whole document exists for.
// F-04.57 is about a schema fact travelling through short-term memory instead of a
// pipe; an executor's context window is that hazard wearing a different uniform.
// So: both halves now enter through committed pipes, or they do not enter.
//
//   node db/queries/format_public_schema.js <csv> <out.md> <YYYY-MM-DD> <ladder-tip>
//
// e.g.
//   node db/queries/format_public_schema.js s0.csv docs/db/PUBLIC_SCHEMA.md 2026-07-23 0096
//
// ── WHAT IT REFUSES TO DO, AND THIS IS THE POINT ────────────────────────
//
// IT WILL NOT WRITE A CAPPED RESULT. public_schema_dump.sql carries a
// self-computing `tables_expected` — a scalar subquery the database evaluates and
// repeats on every row, structurally immune to the SQL editor's row cap. If
// rows_returned < tables_expected the cap bit, and this script EXITS NONZERO
// WITHOUT WRITING. The guard is re-run mechanically here rather than trusted from
// the founder's eye, because F-04.29's founding case is a result silently cut to 99
// rows that nobody noticed. A reference that returns a PARTIAL truth is the disease
// it was built to cure.
//
// ── IT DOES NOT OWN THE WHOLE FILE ──────────────────────────────────────
//
// Everything from the CONSTRAINTS-ADDENDUM sentinel onward is the sibling's
// property and is carried across VERBATIM on every run — read, held, re-appended
// byte-for-byte. This script rewrites the head and never the tail. Re-running is
// idempotent: the column snapshot is replaced, the addendum survives untouched.
//
// ── WHAT IS NOT COMMITTED, NAMED ────────────────────────────────────────
//
// The CSV is NOT committed, following the sibling exactly: the output lives in
// PUBLIC_SCHEMA.md and its raw result set lives nowhere. The re-run path is the
// SQL, not the CSV — which is why the SQL is the committed artifact and is
// founder-runnable on demand. A second home for the same facts is a home that goes
// stale silently.
// ════════════════════════════════════════════════════════════════════
'use strict';

const fs = require('fs');

const SENTINEL = '<!-- CONSTRAINTS-ADDENDUM:BEGIN — generated by db/queries/append_constraints_to_public_schema.js. Everything below this line is script-written. Do not hand-edit. -->';

// ── a CSV parser that handles quoted fields with embedded newlines ────────
// Written rather than depended on, for the sibling's stated reason: columns_detail
// is a multi-line string_agg carrying commas, quotes and newlines inside one field.
// A split(',') would shred it into silently wrong columns and still look green.
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1 || (r[0] || '').trim() !== '');
}

function main() {
  const [, , csvPath, outPath, snapshotDate, ladderTip] = process.argv;
  if (!csvPath || !outPath || !snapshotDate || !ladderTip) {
    console.error('usage: node db/queries/format_public_schema.js <csv> <out.md> <YYYY-MM-DD> <ladder-tip>');
    process.exit(2);
  }

  const rows = parseCsv(fs.readFileSync(csvPath, 'utf8'));
  const header = rows.shift();
  const idx = n => header.indexOf(n);
  const iExp = idx('tables_expected'), iName = idx('table_name'),
        iCols = idx('columns'), iDetail = idx('columns_detail');
  if ([iExp, iName, iCols, iDetail].some(i => i < 0)) {
    console.error('ABORT — unexpected header. Expected the four columns emitted by');
    console.error('        db/queries/public_schema_dump.sql. Got: ' + header.join(','));
    process.exit(1);
  }

  console.log('\n== THE GUARD — tables_expected is computed by the DATABASE and cannot be capped ==\n');

  const expected = Number(rows[0][iExp]);
  if (new Set(rows.map(r => r[iExp])).size !== 1) {
    console.error('ABORT — tables_expected is not constant across rows. The result is not one');
    console.error('        query\'s output. NOTHING WAS WRITTEN.');
    process.exit(1);
  }
  if (rows.length !== expected) {
    console.error(`ABORT — column snapshot: THE CAP BIT. rows_returned=${rows.length}, tables_expected=${expected}.`);
    console.error('        Raise the SQL editor\'s Limit and re-run. NOTHING WAS WRITTEN.');
    console.error('        A capped snapshot reports ABSENCE where there is only TRUNCATION,');
    console.error('        and absence is the fact this document exists to establish.');
    process.exit(1);
  }
  console.log(`  GUARD PASS  column snapshot        rows_returned=${rows.length} == tables_expected=${expected}\n`);

  const totalCols = rows.reduce((a, r) => a + Number(r[iCols]), 0);

  const out = [];
  out.push('# docs/db/PUBLIC_SCHEMA.md — the `public` schema, WITNESSED PROD SNAPSHOT');
  out.push('');
  out.push(`**Snapshot taken:** ${snapshotDate}, founder-run in the Supabase SQL editor, output handed back as CSV and formatted by script. **${expected} tables, ${totalCols} columns.**`);
  out.push(`**Applied ladder tip at snapshot:** \`${ladderTip}\` — stated in the header so this file's staleness is a readable fact, never archaeology. The prior snapshot (2026-07-16, 57 tables) went twenty migrations stale before anyone measured it.`);
  out.push('**Project:** `nvzkbagqxbysoeszxent` (PRODUCTION). **Role: NOT WITNESSED** — the executor did not see this run\'s editor chrome and names that rather than assert it.');
  out.push('**Generated by:** `db/queries/public_schema_dump.sql`. **Regenerate on demand by re-running that file.**');
  out.push('**NEVER HAND-EDIT.** A hand-edited snapshot is prose again, and prose is what this file exists to kill.');
  out.push('');
  out.push(`**THE GUARD PASSED.** The dump's self-computing \`tables_expected\` read **${expected}**; the result carried **${rows.length}** rows. Equal ⇒ the editor's row cap did not truncate this snapshot (F-04.29's disease, made self-detecting). The guard was re-run mechanically at format time, not eyeballed — a capped CSV exits nonzero without writing.`);
  out.push('');
  out.push('**WHY THIS FILE EXISTS — F-04.57.** `ENGINE_SCHEMA.md` covers the `engine` plane only. Without this file the `public` plane — which owns `vendors`, `events`, `leads`, `invoices`, `couples`, `prospects` — has no witnessed column list anywhere: `BASELINE.md` carries counts without names, and `SCHEMA.md`\'s ladder header is stale. *Founder-run SQL is written ONLY against witnessed column lists — never against prose.*');
  out.push('');
  out.push('**⚠ SCOPE — WHAT THIS FILE DOES *NOT* CARRY, NAMED SO THE SILENCE IS NOT MISREAD.** `information_schema.columns` yields column **name, type, nullability and default** — nothing else. CHECK constraints, indexes, foreign keys, triggers and RLS policies are **absent from this half** and live in the CONSTRAINTS ADDENDUM below the sentinel. This half answers *"what columns exist, of what type"*. It does not answer *"what values are legal."* **BASE TABLEs only; views excluded, exactly as the engine twin excludes them.**');
  out.push('');
  out.push('**Ordinal gaps are not errors.** A hole is a dropped column\'s fingerprint — `vendors` runs 1–34 then jumps to 43, `clients` skips 12, `couple_tasks` skips 5. A gap is not an absence.');
  out.push('');
  out.push('---');
  out.push('');

  for (const r of rows) {
    out.push(`## public.${r[iName]}  ·  ${r[iCols]} columns`);
    out.push('');
    out.push('```');
    out.push(r[iDetail].replace(/\r/g, '').trimEnd());
    out.push('```');
    out.push('');
  }

  // The constraints addendum is the sibling's property. Carried across verbatim.
  let tail = '';
  if (fs.existsSync(outPath)) {
    const existing = fs.readFileSync(outPath, 'utf8');
    const cut = existing.indexOf(SENTINEL);
    if (cut >= 0) tail = existing.slice(cut);
  }
  if (tail) out.push(tail);

  fs.writeFileSync(outPath, out.join('\n').replace(/\n+$/, '\n'));
  console.log(`  WROTE ${outPath}`);
  console.log(`  tables ${rows.length} · columns ${totalCols}`);
  console.log(`  constraints addendum: ${tail ? 'PRESERVED VERBATIM (sibling-owned)' : 'none present — run append_constraints_to_public_schema.js next'}\n`);
}

main();
