-- REPO: devjroy-dev/dream-os  ·  db/queries/public_constraints_dump.sql
-- ════════════════════════════════════════════════════════════════════
-- THE PUBLIC CONSTRAINTS DUMP (READ-ONLY) — the addendum to PUBLIC_SCHEMA.md.
-- TDW_04 Part B, the CHECKER sitting. CE-ruled 2026-07-16 (§4.2's third rider).
--
-- ── WHY THIS FILE EXISTS, and it is NOT "more of the same" ───────────────
--
-- public_schema_dump.sql witnessed public's COLUMNS. It did not witness what those
-- columns will REFUSE. Those are different facts and only one of them is in
-- information_schema.columns:
--
--   · `events.slot text` is nullable and carries a CHECK — `slot in ('morning',
--     'noon', 'evening', 'full_day')`. The column list shows the type and the
--     nullability. IT DOES NOT SHOW THE CHECK. An executor reading only the column
--     list would believe `slot` accepts any text.
--   · `events` carries F-04.32's UNIQUE PARTIAL INDEX on the block guarantee. A
--     partial unique index is invisible to a column list and it is the difference
--     between "a second block on a date is a duplicate row" and "a second block on
--     a date is a 23505 the door must catch."
--   · `vendors.slot_capacity` has NO CHECK, deliberately — Q-SP-1 ruled 0 lawful
--     and negative numbers unruled. **THAT ABSENCE IS A FACT THIS DUMP WITNESSES.**
--     Absence is only evidence if you looked; the column list cannot tell you
--     whether nobody added a CHECK or whether you simply cannot see it from there.
--
-- THE OCCUPANCY CHECKER'S EVERY QUERY RIDES ON THESE. It filters `deleted_at is
-- null` and `state <> 'cancelled'` and its comment claims the second is safe
-- *because state is NOT NULL* — a claim the column list happens to support. It
-- reads `slot` against four legal values it got from a migration file's prose. It
-- assumes a date can hold at most one live block. **Each of those is a constraint,
-- and not one of them was read from a witnessed list.**
--
-- F-04.57's law, stated in its own cure's header: *eight columns get read from a
-- witnessed list or not at all.* This file is that law applied to the OTHER half of
-- the schema — the half that says no.
--
-- ── HOW IT TWINS ITS SIBLING (and where it deliberately does not) ────────
--
-- SAME: read-only, founder-run, ONE statement per section so the editor's single
-- result pane shows each whole, output committed by the executor and never
-- hand-edited, no credentials anywhere.
--
-- DIFFERENT — and this is the one departure, disclosed rather than discovered:
-- **THIS FILE IS THREE STATEMENTS, NOT ONE.** Constraints, foreign keys and indexes
-- live in three different catalogs with three different shapes and no honest join
-- across them. Forcing them into one UNION would mean casting unlike columns into a
-- shared text soup — which is how you get a reference that is technically one query
-- and practically unreadable. Three named sections, run in order, pasted back in
-- order. **The row cap applies to each.** Each carries its own self-computing guard,
-- for the same reason its sibling does: F-04.29's silent truncation dropped 12
-- tables from the engine dump and nobody noticed until the defect it was built to
-- cure recurred.
--
-- ── HOW TO USE ──────────────────────────────────────────────────────────
--
-- 1. Run §1, §2, §3 in the Supabase SQL editor, in order. Founder-run.
-- 2. FOR EACH: does the row count equal that section's `rows_expected`? If not,
--    STOP — raise the editor's Limit and re-run. Do not hand back a capped result.
--    A capped constraints list is worse than none: it reports absence where there is
--    only truncation, and absence is the fact this file exists to establish.
-- 3. Hand back all three outputs. The executor appends them to docs/db/
--    PUBLIC_SCHEMA.md as a CONSTRAINTS ADDENDUM, generated by script from the
--    output — NEVER hand-transcribed, exactly as that file's own header demands of
--    its column snapshot.
-- 4. Regenerate on demand by re-running this file. A cure nobody can re-run quietly
--    stops being a cure (Q-SP-5).
--
-- SCOPE, stated so nobody misreads the silence: schema `public`, BASE TABLEs only,
-- matching its sibling exactly. §1 covers CHECK and UNIQUE and PRIMARY KEY
-- constraints; §2 covers FOREIGN KEYs with their referenced table and their delete
-- rule; §3 covers indexes INCLUDING partial ones (the `WHERE` clause is in the
-- definition, which is the only reason F-04.32's guarantee is visible at all).
-- TRIGGERS ARE ABSENT AND THAT IS DELIBERATE — no ruling needs them, and a silent
-- widening of a witnessed reference is how a reference stops being trustworthy.
--
-- READ-ONLY: three SELECTs over pg_catalog / information_schema. No DDL, no DML.
-- Nothing here can mutate anything. No credentials appear and none are needed —
-- it runs inside an authenticated editor session (standing security rule:
-- founder-run recipes never echo live credentials into transcripts).
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- §1. CHECK / UNIQUE / PRIMARY KEY CONSTRAINTS
-- ════════════════════════════════════════════════════════════════════
select
  -- THE SELF-COMPUTING GUARD. A scalar subquery: computed by the database, repeated
  -- on every row, structurally immune to the cap that truncates the set around it.
  (select count(*)
     from pg_constraint pc
     join pg_class pcl on pcl.oid = pc.conrelid
     join pg_namespace pn on pn.oid = pcl.relnamespace
    where pn.nspname = 'public'
      and pcl.relkind = 'r'
      and pc.contype in ('c', 'u', 'p'))                   as rows_expected,
  cl.relname                                               as table_name,
  con.conname                                              as constraint_name,
  case con.contype when 'c' then 'CHECK'
                   when 'u' then 'UNIQUE'
                   when 'p' then 'PRIMARY KEY' end         as constraint_type,
  pg_get_constraintdef(con.oid)                            as definition
from pg_constraint con
join pg_class cl      on cl.oid = con.conrelid
join pg_namespace ns  on ns.oid = cl.relnamespace
where ns.nspname = 'public'
  and cl.relkind = 'r'                                     -- BASE TABLEs only
  and con.contype in ('c', 'u', 'p')
order by cl.relname, con.contype, con.conname;
-- EXPECTED, at the time of writing (2026-07-16, dream-os 5cdf356) — stated as
-- PREDICTIONS TO BE FALSIFIED BY THE OUTPUT, never as numbers to trust:
--   · public.events carries a CHECK on `slot` reading
--     `slot in ('morning','noon','evening','full_day')` — 0075:181's DDL.
--   · public.vendors.slot_capacity carries NO CHECK. Q-SP-1 ruled 0 LAWFUL and
--     negative values UNRULED; 0076 added the column bare. **If a CHECK appears
--     here, a ruling has been overtaken by the database and the executor records it
--     as a finding rather than quietly adjusting this comment.**
--   · IF ANY OF THIS IS WRONG, THE DATABASE IS RIGHT AND THIS COMMENT IS WRONG.


-- ════════════════════════════════════════════════════════════════════
-- §2. FOREIGN KEYS — with the referenced table and the delete rule
-- ════════════════════════════════════════════════════════════════════
select
  (select count(*)
     from pg_constraint pc
     join pg_class pcl on pcl.oid = pc.conrelid
     join pg_namespace pn on pn.oid = pcl.relnamespace
    where pn.nspname = 'public'
      and pcl.relkind = 'r'
      and pc.contype = 'f')                                as rows_expected,
  cl.relname                                               as table_name,
  con.conname                                              as constraint_name,
  pg_get_constraintdef(con.oid)                            as definition
from pg_constraint con
join pg_class cl      on cl.oid = con.conrelid
join pg_namespace ns  on ns.oid = cl.relnamespace
where ns.nspname = 'public'
  and cl.relkind = 'r'
  and con.contype = 'f'
order by cl.relname, con.conname;
-- `pg_get_constraintdef` carries the referenced table, the columns and the ON
-- DELETE rule in one string — which is why this section does not hand-join
-- key_column_usage to constraint_column_usage. That join is the standard recipe and
-- it is ALSO the recipe that silently drops composite keys by matching on
-- ordinal_position. One catalog function, one string, no join to get wrong.
--
-- EXPECTED: `events.linked_binder_id` carries NO FK — F-04.55's entry and the
-- checker's own comment both state that `entity_id` and the binder link are
-- informational only. **This section is where that claim gets witnessed instead of
-- repeated.**


-- ════════════════════════════════════════════════════════════════════
-- §3. INDEXES — including PARTIAL indexes (F-04.32's block guarantee lives here)
-- ════════════════════════════════════════════════════════════════════
select
  (select count(*)
     from pg_indexes
    where schemaname = 'public')                           as rows_expected,
  tablename                                                as table_name,
  indexname                                                as index_name,
  indexdef                                                 as definition
from pg_indexes
where schemaname = 'public'
order by tablename, indexname;
-- ⚠ THE `WHERE` CLAUSE OF A PARTIAL INDEX IS INSIDE `indexdef` AND NOWHERE ELSE.
--   This is the whole reason this section exists rather than being folded into §1.
--   F-04.32's block guarantee is a UNIQUE PARTIAL index — unique on (vendor_id,
--   event_date) WHERE kind = 'blocked' AND deleted_at IS NULL, per 0075's DDL. Read
--   without its predicate it looks like a unique index that would forbid a vendor
--   two events on one date, which would be catastrophic and false. **A constraint
--   read without its predicate is a constraint misread.**
--
-- EXPECTED: one unique partial index on public.events implementing the block
-- guarantee; a supporting index on (vendor_id, event_date). Predictions, to be
-- falsified by the output.
